[PCOMM SCRIPT HEADER]
LANGUAGE=VBSCRIPT
DESCRIPTION=
[PCOMM SCRIPT SOURCE]
OPTION EXPLICIT
autECLSession.SetConnectionByName(ThisSessionName)
    setUpMacro
    sub setUpMacro()
        autECLSession.autECLOIA.WaitForAppAvailable
        autECLSession.autECLOIA.WaitForInputReady
        moveToCorrectCursorPos 7, 20
        if FindScreenText(34, 3, 13) = "CMS Main Menu" Then
            makeLogin
        else
            MsgBox("Please start on the CMS Main Menu")
        end if
    end sub

Hello